### ISSUE TITLE
Custom Blocks Translations

### ISSUE THREAD

**Issue by bureaunoir** [johannschopplich/kirby-content-translator#13]
Hello,

thank you for the plugin. However i have a problem. The Plugin isn't
translating custom blocks for me. 

```
sections:
     main:
        width: 2/3
        fields:
          text:
            type: text
          blocks:
            type: blocks
            fieldsets:
              - heroBlock
              - sliderBlock
              - tableBlock
              - textBlock
              - interviewsBlock
              - tabsBlock
              - sponsorsBlock
      right:
        width: 1/3
        sections:
          contentTranslator:
            type: content-translator
            syncableFields:
              - text
              - blocks
            translatableFields:
              - text
              - blocks
            translatableBlocks:
              heroBlock:
                - preheadline
                - headline
                - text
```

But when i click on translate, the fields are not translated.
Thank you in advance for your help.
