### ISSUE TITLE
Blocks field inside of custom block throws error when translating

### ISSUE THREAD

**Issue by davidjablonski** [johannschopplich/kirby-content-translator#4]
When adding a custom block type via `translatableBlocks` that contains a blocks field itself, an error is thrown during translation.

This is my custom block called `toggle.yml`.

```
name: Toggle
fields:
  label:
    type: text
  blocks:
    type: blocks
    fieldsets:
      - heading
      - text
```

Adding it to my `translatableBlocks` will throw an error when translating. When removing the blocks field reference, the label is translated correctly and no error is thrown.

```
translatableBlocks:
  toggle:
  - label
  - blocks
```
