### ISSUE TITLE
Structure field in block

### ISSUE THREAD

**Issue by tillschander** [johannschopplich/kirby-content-translator#6]
Hi and thanks creating this plugin.

I noticed that it currently doesn't work yet with blocks who contain structure fields. For example one might define a custom block like so:
```yaml
name: myblock
wysiwyg: true
preview: fields
fields:
  items:
    label: Items
    type: structure
    fields:
      title:
        label: Title
        type: text
      text:
        label: Text
        type: text
````

As is the plugin would not be able to translate this block. To fix that i have written a small patch for your code. The code might not be ideal yet, but it could be a starting point for you to develop an even better solution. You can see it in the linked Pull Request.

With this patch one would define the translatable fields in the structure of the block as follows:
```php
'johannschopplich.content-translator' => [
    'translatableFields' => ['blocks'],
    'translatableBlocks' => [
        'myblock' => [
            'items' => ['title', 'text']
        ],
    ],
],
```
